### ISSUE TITLE
New -Wextra warnings

### ISSUE THREAD

**Issue by FreddieChopin** [CANopenNode/CANopenNode#179]
When you enable -Wextra for GCC, current CANopenNode code gives a few new warnings. There are two categories of these warnings for which I don't have an opinion about what to do with them.

1. In CO_LSS.h there are following macros: `CO_LSS_BIT_TIMING_VALID()`, `CO_LSS_FASTSCAN_BITCHECK_VALID()` and `CO_LSS_FASTSCAN_LSS_SUB_NEXT_VALID()`. These macros (among other things) compare the argument to zero. As in the code these macros are passed an `uint8_t` value exclusively, this results in warnings such as this:
```
./305/CO_LSS.h:157:57: warning: comparison is always true due to limited range of data type [-Wtype-limits]
  157 | #define CO_LSS_FASTSCAN_LSS_SUB_NEXT_VALID(index) (index>=CO_LSS_FASTSCAN_VENDOR_ID && index<=CO_LSS_FASTSCAN_SERIAL)
      |                                                         ^~
305/CO_LSSslave.c:295:10: note: in expansion of macro ‘CO_LSS_FASTSCAN_LSS_SUB_NEXT_VALID’
  295 |         !CO_LSS_FASTSCAN_LSS_SUB_NEXT_VALID(lssNext)) {
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I see three options:
- drop the part that compares the argument with zero, as it makes no sense for an unsigned type anyway,
- cast the argument to `int`,
- convert the macro to inline function taking an unsigned argument and also drop the comparison with zero, making it clear that the argument must be unsigned.

2. There're quite a lot of places which produce a "unused parameter" warning. Normally I would just silence that with casting to `(void)`, but most of these places look like a work-in-progress functions which are not yet implemented completely. These are the warnings in CO_LSSslave.c and CO_LSSmaster.c:
- `CO_LSSslave_serviceSwitchStateGlobal()` - `service`
- `CO_LSSslave_serviceInquire(`) - `msg`
- `CO_LSSslave_process()` - `activeBitRate`
- `CO_LSSmaster_FsScanInitiate()` and `CO_LSSmaster_FsVerifyInitiate()` - `timeDifference_us`.

Is this really the case - are these functions not yet finished, or maybe they just have to fit some API and thus require these arguments, which will be unused anyway?

**Comment by martinwag** [comment]
Hi,

1.

Those are range checks VALID(var) (var>=min && var<=max). 
- I want to have both limit checks there for completeness, if one always computes to "true", compiler can optimize it out. 
- If we don't want a compiler warning, disable it instead of ignoring by "int" cast

I also don't see that a comparision "uint var >=0" is forbidden/undefined behaviour within C standard?

2. 

CO_LSSslave_serviceSwitchStateGlobal() 
CO_LSSslave_serviceInquire() 
both used within CO_LSSslave_receive(), for simplicity of interface all functions use same parameters.

CO_LSSslave_process() 
CO_LSSmaster_FsScanInitiate() and CO_LSSmaster_FsVerifyInitiate()
part of API, where I included them for completeness (avoid API changes for future changes). 


My opinion on this (more on "let's enable all warnings") is that doing static code analysis, unit testing and _temporarily_ enabling all warnings, and **interpreting results**, is time more efficiently spent than trying to get rid of all the warnings that really just should be hints...
