### ISSUE TITLE
CANopenNode on MBED os 5

### ISSUE THREAD

**Issue by geobruce** [CANopenNode/CANopenNode#97]
Hi

I'm working with MBED os 5 on a STM32F091RC (NUCLEO-F091RC) and I'm searching for a CANopenNode implementation which is compatible with MBED os 5.

Or is it possible to just use this configuration: https://github.com/CANopenNode/CANopenNode/blob/master/stack/STM32/CO_driver.c ? 

I'm unsure because on the homepage in the table: Microcontroller support there is no status known for STM32.

All tips and tricks are welcome.

Thank you in advance.

**Comment by WillyKaze** [comment]
Hi, 




If you need any pointers to get you started, you can have a look at the LPC1768 implementation which is compatible with Mbed 5.


https://github.com/CANopenNode/CANopenNode/blob/master/stack/LPC1768/CO_driver.cpp




On Fri, Apr 5, 2019 at 4:24 PM +0200, "geobruce" <notifications@github.com> wrote:












Hi


I'm working with MBED os 5 on a STM32F091RC (NUCLEO-F091RC) and I'm searching for a CANopenNode implementation which is compatible with MBED os 5.


Or is it possible to just use this configuration: https://github.com/CANopenNode/CANopenNode/blob/master/stack/STM32/CO_driver.c ?


I'm unsure because on the homepage in the table: Microcontroller support there is no status known for STM32.


All tips and tricks are welcome.


Thank you in advance.

**Comment by geobruce** [comment]
> Hi, If you need any pointers to get you started, you can have a look at the LPC1768 implementation which is compatible with Mbed 5. https://github.com/CANopenNode/CANopenNode/blob/master/stack/LPC1768/CO_driver.cpp 

Thank you I'll have a look at it. Is there somewhere else some documentation on how to use the library?

**Comment by geoffrey-vl** [comment]
Issue is covered here: https://github.com/Alphatronics/CANopenNode/tree/mbedSTM32

please close

**Comment by martinwag** [comment]
please add your driver to the wiki https://github.com/CANopenNode/CANopenNode/wiki when finished, so others can find it.
