### ISSUE TITLE
Clarify that RTR is unsupported by CANopenNode

### ISSUE THREAD

**Issue by follower** [CANopenNode/CANopenNode#99]
It would be helpful to clarify here that transmission types 252 & 253 are valid according to the specification but explicitly not implemented/supported by CANopenNode:

https://github.com/CANopenNode/CANopenNode/blob/533801574055c5dacf60fb6b18930c288336dce1/stack/CO_PDO.c#L559-L561

For additional background see: https://github.com/CANopenNode/CANopenNode/issues/98#issuecomment-485402918

**Comment by follower** [comment]
Also here: https://github.com/CANopenNode/CANopenNode/blob/533801574055c5dacf60fb6b18930c288336dce1/stack/CO_PDO.h#L140

**Comment by mjphillips1981** [comment]
Thank you.  I found those lines of code as well.  I am thinking that the competitor unit that I have is using some custom firmware to handle their RTR response for the TPDO.  Because the device does not need to be set to 252 or 253 to use RTR.  I am just going to omit this in my device.  The same results can be acquired using the SYNC method.
